### ISSUE TITLE
金融のワークスペースだとLazyリスナーが動作しない

### ISSUE THREAD

**Issue by takuya-okamoto-esm** [esminc/boat-bee#250]
### 問題
金融メンバーが「おすすめの本を確認する」ボタンを押しても期待するモーダルが表示されない

#### 現象1
金融メンバが一人だけで実行すると
- 「処理中」から更新されない

金融メンバーが二人同時に実行すると
- 一人目は「処理中」から更新されない
- 二人目はSlackAppでエラーが表示される

（三田村、見澤で確認）
上記の振る舞いは個人について回るのではなく、操作順に影響されているように見える

#### 現象2
ITSメンバーが実行すると上記の問題は起きていない
（岡島、坂部、岡本で確認）

### 環境
AWS本番環境

### 発生バージョン
発見したのは5/24 リリース予定のリコメンド機能公開バージョン

```
Commit: 6de5f560f2289ae7df78f40ae1e80c49283a0366
Parents: 8dc310e3b6dab015ef491b3a0d01711fa759bf88, 670339051c80eeb18bd74c58af1ac2f17c198f06
Author: Hiroki SAKABE <[hiroki.sakabe@esm.co.jp](mailto:hiroki.sakabe@esm.co.jp)>
Committer: GitHub <[noreply@github.com](mailto:noreply@github.com)>
Date: Tue May 24 2022 11:30:09 GMT+0900 (日本標準時)
 

Merge pull request #242 from esminc/collaborative-filtering

アイテムベース協調フィルタリングの初期コードを実装
```

ただしそれより前の版に戻して試したところ、同じ現象が出ているので
この問題は今回のリリース内容とは無関係と思われる。

**Comment by hirokisakabe** [comment]
インストール先をワークスペース ESM, Inc.に変更し、Slack Connect経由での利用はされなくなったのでclose
